name: liberated-chat
version: 1.1.4
description: Probably the simplest minecraft plugin that disables chat reporting.
authors: [Blay, Timongcraft]
website: https://modrinth.com/plugin/liberated-chat

api-version: 1.20
main: com.blay.liberatedchat.LiberatedChat
